# Generated by Django 4.0.6 on 2022-08-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='brend',
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.CharField(default='any', max_length=32),
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('production_year', models.CharField(max_length=16)),
                ('milage', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.category')),
            ],
        ),
    ]
