# Generated by Django 4.0.6 on 2022-08-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_name_category_brend_category_country_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicles',
            name='age',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='app01.age'),
        ),
    ]
