# Generated by Django 4.0.6 on 2022-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_age_vehicles_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.CharField(max_length=16),
        ),
    ]
