# Generated by Django 4.0.6 on 2022-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_age_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='age',
        ),
        migrations.AddField(
            model_name='age',
            name='age_big_scale',
            field=models.CharField(default='skip', max_length=16),
        ),
        migrations.AddField(
            model_name='age',
            name='age_small_scale',
            field=models.CharField(default='skip', max_length=16),
        ),
    ]
