# Generated by Django 4.0.6 on 2022-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_age_age_age_age_big_scale_age_age_small_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='age',
            field=models.IntegerField(default=101),
        ),
    ]
