# Generated by Django 4.0.6 on 2022-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_age_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='mark',
            field=models.CharField(default='any', max_length=32),
        ),
    ]
