# Generated by Django 4.0.6 on 2022-08-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_remove_category_description_category_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='type',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='category',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='model',
            field=models.CharField(default='not given', max_length=32),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
