# Generated by Django 4.0.6 on 2022-08-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_type_vehicles_brand_remove_vehicles_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='age',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='age',
        ),
        migrations.AddField(
            model_name='age',
            name='production_year',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='engine',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='production_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.age'),
        ),
    ]
