# Generated by Django 4.0.6 on 2022-08-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_remove_age_age_remove_vehicles_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='production_year',
            field=models.IntegerField(unique=True),
        ),
    ]
