# Generated by Django 4.0.6 on 2022-08-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_age_production_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='milage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.mileage'),
        ),
    ]
