# Generated by Django 4.0.6 on 2022-08-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_mileage_alter_vehicles_milage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='km',
            field=models.IntegerField(default=1),
        ),
    ]
